[WIP] Prepare for product selection
yast/skelcd-control-leanos pull request #1
Opened 2017-07-19 10:07 UTC by jreidinger

2017-07-27 13:34 UTC, lslezak approved these changes
LGTM

2017-07-31 08:05 UTC, teclator commented on README.md
> +everythin any add-on can do. Also LeanOS can be installed itself, so it have its control.xml and
everything

2017-07-31 08:06 UTC, jreidinger commented on README.md
> +everythin any add-on can do. Also LeanOS can be installed itself, so it have its control.xml and
thanks

2017-07-31 13:15 UTC, teclator commented on README.md
> +everythin any add-on can do. Also LeanOS can be installed itself, so it have its control.xml and
In general it should need a whole review of the third person use .. or not used at all :P

2017-07-31 13:53 UTC, teclator commented on README.md
> +everythin any add-on can do. Also LeanOS can be installed itself, so it have its control.xml and
What about something like:

LeanOS adds the capability to install independent products with the same media.

It has its own control.xml file which has reasonable defaults for almost all except partitioning.

Its workflow ends up with a product selection client, and there is where comes to play the `installation.xml` specific product file. It is a common add-on installation xml that can do everything an add-on can do. You can read more about the add-on installation.xml in this [document](https://github.com/yast/yast-installation/blob/master/doc/control-file.md#control-sectionadd-on-product-installation-workflow-specification)

But LeanOS is a product itself so apart of the `control.xml` file it also has its own `installation.xml`.

2017-08-02 08:39 UTC, lslezak requested changes

2017-08-02 08:39 UTC, lslezak commented on README.md
> +Product selector in installator basically search for any product. Then for each product it try to
Sounds too complicated to me, I'd replace the whole paragraph with this text:

The product selector dialog in the installation displays all products for which exists a `system-installation() = <product_name>` provides dependency. When a product is selected then its corresponding package providing the system installation is unpacked and its `installation.xml` file is used to continue with the installation.

2017-08-02 08:51 UTC, lslezak approved these changes

2017-08-02 08:58 UTC, merged